# -*- coding: utf-8 -*-
"""find_colab_fonts.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WoN-RLOP3iPjqIUw1ATpg1Y-M9B5rvYZ
"""

import os
os.getcwd()

import pandas as pd
test_df = pd.DataFrame([])
test_df.to_csv('test.csv')

import subprocess
p = subprocess.Popen(["find", "..", "-type", "f", "-name", "*.ttf"], stdout=subprocess.PIPE)
print(type(p))
#p = subprocess.Popen(["find . -type f -name \"*.txt\""], stdout=subprocess.PIPE)

pd.Series(p.communicate())[0].decode("utf-8").split('\n')



test_str = "../usr/share/fonts/truetype/liberation/LiberationSans-BoldItalic.ttf\\n../usr/share/fonts/truetype/liberation/LiberationSansNarrow-Bold.ttf\\n"
test_str.split('\\n')